MOS:
# enabled: true
  mosWeightsDir: "/root/MOS_Codes/benchmark/mos_weights.csv"
  scoringFunctions:
  - name: getNetScore
    weightHeader: net_weight
    path: /root/MOS_Codes/mos_scores.py
  - name: getCpuScore
    weightHeader: cpu_weight
    path: /root/MOS_Codes/mos_scores.py
  - name: getCostForNodes
    weightHeader: cost_weight
    path: /root/MOS_Codes/mos_scores.py
  deploymentFile: /root/bookinfo/deploy/bookinfo-netMarks.yaml
# scoreFunctions:
# - name: getNetScore
#   path: /root/MOS_Codes/mos_scores.py
#   weight: 1
# - name: getCpuScore
#   path: /root/MOS_Codes/mos_scores.py
#   weight: 5
# - name: getCostForNodes
#   path: /root/MOS_Codes/mos_scores.py
#   weight: 1
microService:
  name: bookinfo
  appList:
  - name: details
  - name: ratings
  - name: reviews-v1
  - name: reviews-v2
  - name: reviews-v3
  - name: productpage
database:
  shouldInitDb: true # create DB; if it is true, shouldCollectData should be true
  location: /root/MOS_Codes/testDatabase.db # new DB save location or old db path
telemetry:
  prometheus:
    strategy:
      name: serviceQuery
      match: startsWith
      value: prometheus
dataCollection:
  shouldCollectData: true # if false, no data will be collected for scheduling, already existing data will be used
  minute: 12
  userCounts:
    - 50
    - 1000
    # - 2000
svcToSendLoad: "productpage"
locustFileLocation: "/root/bookinfo/bench/locustfile.py"
benchmark:
  dataSaveDir: /root/MOS_Codes/dataTesting # no / at the end please
  enabled: true
  locustFileLocation: "/root/bookinfo/bench/locustfile.py"
  svcToSendLoad: "productpage"
  repetitions: 1
  restPeriod: 5 # not much important
  loadTime: 15 # seconds
  userCounts:
    - 10
    # - 1000
    # - 2000
  startMOSNumberingFrom: 1
  baselines:
  - name: default
    schedulerFunction: "runDefaultScheduler"
    startNumberingFrom: 1001
    deploymentFile: /root/bookinfo/deploy/bookinfo.yaml
  - name: binpack
    schedulerFunction: runBinpackScheduler
    startNumberingFrom: 2001
    deploymentFile: /root/bookinfo/deploy/bookinfo-binPack.yaml
  - name: netMarks
    schedulerFunction: runNetMarksScheduler
    startNumberingFrom: 3001
    deploymentFile: /root/bookinfo/deploy/bookinfo-netMarks.yaml
