---
kind: PersistentVolume
apiVersion: v1
metadata:
  name: loki-pv
  labels:
    type: local
spec:
  storageClassName: standard
  capacity:
    storage: 12Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/home/ubuntu"
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - "k8s-vm1"
          - "k8s-vm2"
---